graph TD
    %% Shapes: (()) heart, [] fortress/settlement, {{}} dungeon/lair, >] sanctuary, ([]) waypoint, [//] tower/ruin

    blackwater_crossing(("Blackwater Crossing\n1010"))
    abandoned_farmhouse[/"The Cursed Farmhouse\n1011"\]
    graveyard(["The Graveyard\n1007"])
    kalla_cave{{"Kalla Cave\n1207"}}
    mud_wallow>"The Mud Wallow\n0906"]
    pjork_choppe_hille["Pjörk Choppe Hille\n0905"]
    crag_cairn{{"Crag Cairn\n1005"}}
    kobold_crevasse["The Kobold Crevasse\n1105"]
    fae_glade>"The Fae Glade\n0805"]
    thornespire_keep["Thornespire Keep\n0705"]
    ravens_perch[/"Raven's Perch\n0904"\]
    the_swamp("The Swamp\n0504")
    mistwood_glen>"Mistwood Glen\n0912"]
    south_road_mountain_watch(["Brunhilde's Mountain Watch Camp\n1112"])
    serpents_pass(["Serpent's Pass\n1113"])
    bandit_camp{{"Bandit Ambush Hill\n1113"}}
    tower_of_stargazer[/"Tower of the Stargazer\n0913"\]
    vault_of_first_light{{"Vault of First Light\n1215"}}
    north_road(["The North Road\n1005"])
    south_pass(["The South Pass\n1216"])
    northern_warding_stone>"Northern Warding Stone\n0906"]
    southern_warding_stone>"Southern Warding Stone\n0707"]

    %% Links: === road, --- trail, -.- wilderness
    blackwater_crossing ===|"Old Northern Trade Road, 1.5d"| south_road_mountain_watch
    south_road_mountain_watch ===|"Old Northern Trade Road, 0.5d"| serpents_pass
    serpents_pass ===|"Old Northern Trade Road, 1.0d"| south_pass
    pjork_choppe_hille -.-|"Path Through the Wood, 0.5d"| fae_glade
    fae_glade -.-|"Forest Path to Thornespire, 0.5d"| thornespire_keep
    mud_wallow -.-|"Forest Path to Crag Cairn, 0.25d"| crag_cairn
    crag_cairn -.-|"Path to the Kobold Crevasse, 0.17d"| kobold_crevasse
    north_road ---|"Forest Trail to Raven's Perch, 0.25d"| ravens_perch
    blackwater_crossing ---|"Path to the Farmhouse, 0.1d"| abandoned_farmhouse
    blackwater_crossing ---|"Trail to Mistwood Glen (via 1012), 2.5d"| mistwood_glen
    serpents_pass -.-|"Path to the Vault, 1.0d"| vault_of_first_light
    serpents_pass -.-|"Foothills Trail West, 0.5d"| tower_of_stargazer
    tower_of_stargazer ---|"Path to Hangman Hill, 0.1d"| bandit_camp
    mud_wallow ---|"Path to the Warding Stone, 0.1d"| northern_warding_stone
    southern_warding_stone -.-|"Vampire Ward Line"| northern_warding_stone
    north_road ===|"Old Northern Trade Road, 1.0d"| blackwater_crossing
    graveyard ---|"Trail to Kalla Cave, 0.5d"| kalla_cave
    north_road ===|"0.5d"| thornespire_keep
    north_road -.-|"Forest Track to Pjörk Choppe Hille, 0.5d"| pjork_choppe_hille
    north_road -.-|"Trail to the Kobold Crevasse, 0.5d"| kobold_crevasse
    north_road ---|"Trail to the Mud Wallow, 0.25d"| mud_wallow